# 環境変数
export LANG=ja_JP.UTF-8

# 色を使用出来るようにする
autoload -Uz colors
colors

# ヒストリの設定
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000


# 単語の区切り文字を指定する
autoload -Uz select-word-style
select-word-style default
# ここで指定した文字は単語区切りとみなされる
# / も区切りと扱うので、^W でディレクトリ１つ分を削除できる
zstyle ':zle:*' word-chars " /=;@:{},|"
zstyle ':zle:*' word-style unspecified

# 補完
# 補完機能を有効にする
autoload -Uz compinit
compinit

# 補完で小文字でも大文字にマッチさせる
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# ../ の後は今いるディレクトリを補完しない
zstyle ':completion:*' ignore-parents parent pwd ..

# sudo の後ろでコマンド名を補完する
zstyle ':completion:*:sudo:*' command-path /usr/local/sbin /usr/local/bin \
                   /usr/sbin /usr/bin /sbin /bin /usr/X11R6/bin

# ps コマンドのプロセス名補完
zstyle ':completion:*:processes' command 'ps x -o pid,s,args'


# vcs_info
autoload -Uz vcs_info
zstyle ':vcs_info:*' formats '(%s)-[%b]'
zstyle ':vcs_info:*' actionformats '(%s)-[%b|%a]'
# プロンプト表示前に呼ばれる関数
precmd () {
    psvar=()
    LANG=en_US.UTF-8 vcs_info
    [[ -n "$vcs_info_msg_0_" ]] && psvar[1]="$vcs_info_msg_0_"
		setprompt
}
COLOR_R="%{[38;5;219m%}"      # 色の変更
COLOR_END="%{[0m%}"            # 色を元に戻す
RPROMPT="%1(v|${COLOR_R}%1v${COLOR_END}|)"

# virtualenvでpromptを変更しない
export VIRTUAL_ENV_DISABLE_PROMPT=1

# プロンプトの表示: virtualenv対応版
function setprompt(){
   PYTHON_VIRTUAL_ENV_STRING=""
   if [ -n "$VIRTUAL_ENV" ]; then
     PYTHON_VIRTUAL_ENV_STRING=":`basename \"$VIRTUAL_ENV\"`"
   fi
	# 色設定
	# 
	COLOR_C="%{[38;5;166m%}"      # 色の変更
	COLOR_Y="%{[38;5;051m%}"      # 色の変更
	COLOR_K="%{[38;5;040m%}"      # 色の変更
	COLOR_END="%{[0m%}"            # 色を元に戻す
	PROMPT="${COLOR_C}[%n@%m] ${COLOR_Y}%~ ${COLOR_K}${PYTHON_VIRTUAL_ENV_STRING}${COLOR_END}
% $ "
}


# 日本語ファイル名を表示可能にする
setopt print_eight_bit
# beep音を消す
setopt no_beep
# フローコントロールを無効にする
setopt no_flow_control
# '#' 以降をコメントとして扱う
setopt interactive_comments
# ディレクトリ名だけでcdする
setopt auto_cd
# cd したら自動的にpushdする
setopt auto_pushd
# 重複したディレクトリを追加しない
setopt pushd_ignore_dups
# = の後はパス名として補完する
setopt magic_equal_subst
# 同時に起動したzshの間でヒストリを共有する
setopt share_history
# 同じコマンドをヒストリに残さない
setopt hist_ignore_all_dups
# ヒストリファイルに保存するとき、すでに重複したコマンドがあったら古い方を削除する
setopt hist_save_nodups
# スペースから始まるコマンド行はヒストリに残さない
setopt hist_ignore_space
# ヒストリに保存するときに余分なスペースを削除する
setopt hist_reduce_blanks
# 補完候補が複数あるときに自動的に一覧表示する
setopt auto_menu
# 高機能なワイルドカード展開を使用する
setopt extended_glob



# ^R で履歴検索をするときに * でワイルドカードを使用出来るようにする
bindkey '^R' history-incremental-pattern-search-backward

# 補完候補にも色を付ける
# zstyle ':completion:*' list-colors di=34 ln=35 ex=31


########################################
# エイリアス

alias la='ls -a'
alias ll='ls -l'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'

# sudo の後のコマンドでエイリアスを有効にする
alias sudo='sudo '

# グローバルエイリアス
alias -g L='| less'
alias -g G='| grep'

# git のエイリアス
alias st='git status'

# 文字コード
set encoding=utf-8

case ${OSTYPE} in
    darwin*)
        #Mac用の設定
        export CLICOLOR=1
        alias ls='ls -G -F'
				export PATH=/usr/local/bin:/usr/bin:/bin
				# sysctl
				export PATH=$PATH:/usr/sbin/
				# pyenv
				export PYENV_ROOT=$HOME/.pyenv
				export PATH="$HOME/.pyenv/bin:$PATH"
				eval "$(pyenv init -)"
				eval "$(pyenv virtualenv-init -)"
        ;;
    linux*)
				alias ls='ls --color=auto'
				# squid only
        export PYENV_ROOT=$HOME/.pyenv
        export PATH=$PYENV_ROOT/bin:$PATH
        eval "$(pyenv init -)"
				export PATH=$PATH:/usr/local/bin:/usr/bin:/bin
        ;;
esac
